### DISCUSSION TITLE
CSS Script only works when page is reloaded

### DISCUSSION THREAD

**Discussion by marlonjames71** [quoid/userscripts#753] [Q&A] [answered]
I have a CSS script for hiding scrollbars only on YouTube's website, but it never works when the page first loads or when I click on different videos. Only when I refresh the page. Can anyone suggest what I should do to get this to work reliably the first time it loads and for any video I click on without having to reload every time?

Here's the very simple script:
```css
/* ==UserStyle==
@name        Hide YT Scrollbar
@description Hides the scrollbar on YouTube
@match        *://*.youtube.com/*
@exclude      *://music.youtube.com/*
@exclude      *://*.music.youtube.com/*
==/UserStyle== */

body::-webkit-scrollbar { width: 0px; !important; }
```

**Comment by ACTCD** [comment]
There's a syntax error there, an extra semicolon.

```css
body::-webkit-scrollbar { width: 0px !important; }
```

Also due to #711, it is recommended to use `.user.js` instead of `.css`.
The custom `==UserStyle==` support will be deprecated in the future.
