### ISSUE TITLE
new css import from GitHub does not work

### ISSUE THREAD

**Issue by maximilianotaverna** [quoid/userscripts#101]
example 

@import url('https://raw.githubusercontent.com/maximilianotaverna/CleanSearch-CSS/master/googlesearch_rule.css');

**Comment by quoid** [comment]
Can you please provide the userscript, *with* metadata?

Unfortunately your description is vague so I am not entirely sure what the issue is. If it has to do with `@import` on css code userscripts - that is working as intended on my machine. Perhaps you can also provide the your system specs (the question asked before submitting an issue)?

If my guess is correct and the issue *does* have to do with `@import`below is an example using it. You can install that userscript and visit `https://www.k21p.com` and see that "Pacifico" font is being used, which was imported. If you toggle the item off, you will see a different font being used. 

```css
/* ==UserStyle==
@name        _TestImport
@description This is your new file, start writing code
@match       *://*k21p.*
@requireC https://raw.githubusercontent.com/maximilianotaverna/CleanSearch-CSS/master/googlesearch_rule.css
==/UserStyle== */

@import url("https://fonts.googleapis.com/css2?family=Pacifico&display=swap");

body {
    font-family: Pacifico, impact, serif;
}
```
