### ISSUE TITLE
finance.yahoo must reload

### ISSUE THREAD

**Issue by TraderStf** [quoid/userscripts#117]
_System Information:_
> macOS version: 11.2.3
> Userscripts version: 31
> Safari version: 14.03

Thanks for such a nice tool!

I made a script for finance.yahoo.com
.gemini-ad {display:none !important}

but must reload the page to get rid of the ads.

Sorry, I'm not used to this kind of "delete"
I have tried a ~getelementby... remove() but did not work.

thanks

**Comment by quoid** [comment]
@TraderStf 

Can you please paste the entire userscripts you have tried? 

Thanks

**Comment by TraderStf** [comment]
My script was without a doubt bad. Something like, I delete it
var yads = document.getElementsByClassName('gemini-ad');
yads.remove();

then another try with a ForEach

My goal was to avoid loading the ads, as the display:none just hide it.
But it's perhaps useless as the script acts after the download.

Don't worry, thank you so much for this great tool!

**Comment by quoid** [comment]
@TraderStf 

I made a small test `css` userscript:

```css
/* ==UserStyle==
@name        Test Yahoo
@description This is your new file, start writing code
@match       *://finance.yahoo.com/*
==/UserStyle== */

.gemini-ad {
    display: none;
}
```

It seems to function as intended on [finance.yahoo.com](finance.yahoo.com), without the need to reload.

If you have time, could you test it on your machine and let me know if it works? Click `+`, then `New CSS` and then paste the above code. It's best to test with all other userscripts disabled as they could be the cause of the issues.
